### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by NicolasCARPi** [outscale-dev/osc-bsu-backup#10]
Hello,

I came across this project while trying to figure out the best way to rotate my snapshots with `osc-cli`. This is exactly what I'm looking for except:

- it is not available through `pip` (pypi.org), is that something you're planning to do? It would make installation/updates easier with automation tools
- it uses aws credentials and tooling, could it rather use the `osc-cli` and `~/.osc/config.json` config instead? It seems `osc-cli` doesn't support Tags, right? So maybe that's why you are using the aws tooling?

Side note: shouldn't this line: https://github.com/outscale-dev/osc-bsu-backup/blob/master/osc_bsu_backup/cli.py#L40 be `osc-bsu-backup` instead?

Best,
~Nico

**Comment by outscale-rjt** [comment]
Hello Nicolas

* we're gonna considerate to push the package on pypi, since we already do it for osc-cli
* the tool need a complete rewrite to use osc-cli, it's not planned for the moment but it's in our todo
